# Generated by Django 6.0.2 on 2026-02-04 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Responsavel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('tipo', models.CharField(choices=[('pai', 'Pai'), ('mae', 'Mae'), ('responsavel_legal', 'Responsavel legal')], max_length=20, verbose_name='tipo')),
                ('ativo', models.BooleanField(default=True, verbose_name='ativo')),
                ('pessoa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='responsavel', to='people.pessoa', verbose_name='pessoa')),
            ],
            options={
                'verbose_name': 'responsavel',
                'verbose_name_plural': 'responsaveis',
                'ordering': ['pessoa__nome'],
            },
        ),
        migrations.CreateModel(
            name='AlunoResponsavel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('tipo_vinculo', models.CharField(choices=[('pai', 'Pai'), ('mae', 'Mae'), ('tutor', 'Tutor')], max_length=20, verbose_name='tipo de vinculo')),
                ('responsavel_principal', models.BooleanField(default=False, verbose_name='responsavel principal')),
                ('autorizado_retirar_aluno', models.BooleanField(default=True, verbose_name='autorizado a retirar o aluno')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='responsaveis', to='people.aluno', verbose_name='aluno')),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alunos', to='people.responsavel', verbose_name='responsavel')),
            ],
            options={
                'verbose_name': 'aluno-responsavel',
                'verbose_name_plural': 'alunos-responsaveis',
                'ordering': ['aluno', 'responsavel'],
                'constraints': [models.UniqueConstraint(fields=('aluno', 'responsavel'), name='unique_aluno_responsavel')],
            },
        ),
    ]
