# Generated by Django 6.0.2 on 2026-02-04 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnoLetivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('nome', models.CharField(max_length=20, unique=True, verbose_name='nome')),
                ('data_inicio', models.DateField(verbose_name='data de inicio')),
                ('data_fim', models.DateField(verbose_name='data de fim')),
                ('ativo', models.BooleanField(default=True, verbose_name='ativo')),
            ],
            options={
                'verbose_name': 'ano letivo',
                'verbose_name_plural': 'anos letivos',
                'ordering': ['-nome'],
            },
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('nome', models.CharField(max_length=200, verbose_name='nome')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='codigo')),
                ('carga_horaria', models.PositiveIntegerField(verbose_name='carga horaria (h/ano)')),
                ('ativa', models.BooleanField(default=True, verbose_name='ativa')),
            ],
            options={
                'verbose_name': 'disciplina',
                'verbose_name_plural': 'disciplinas',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('nome', models.CharField(max_length=100, verbose_name='nome')),
                ('ativa', models.BooleanField(default=True, verbose_name='ativa')),
                ('ano_letivo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='turmas', to='academic.anoletivo', verbose_name='ano letivo')),
                ('escola', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='turmas', to='core.escola', verbose_name='escola')),
            ],
            options={
                'verbose_name': 'turma',
                'verbose_name_plural': 'turmas',
                'ordering': ['ano_letivo', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='AlunoTurma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('data_matricula', models.DateField(verbose_name='data de matricula')),
                ('ativo', models.BooleanField(default=True, verbose_name='ativo')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='turmas_matriculadas', to='people.aluno', verbose_name='aluno')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alunos_matriculados', to='academic.turma', verbose_name='turma')),
            ],
            options={
                'verbose_name': 'aluno-turma',
                'verbose_name_plural': 'alunos-turmas',
                'ordering': ['turma', 'aluno'],
            },
        ),
        migrations.CreateModel(
            name='ProfessorDisciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('ano_letivo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='professor_disciplinas', to='academic.anoletivo', verbose_name='ano letivo')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='professores_vinculados', to='academic.disciplina', verbose_name='disciplina')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='disciplinas_lecionadas', to='people.professor', verbose_name='professor')),
            ],
            options={
                'verbose_name': 'professor-disciplina',
                'verbose_name_plural': 'professores-disciplinas',
                'ordering': ['ano_letivo', 'professor', 'disciplina'],
                'constraints': [models.UniqueConstraint(fields=('professor', 'disciplina', 'ano_letivo'), name='unique_prof_disc_ano')],
            },
        ),
        migrations.AddConstraint(
            model_name='turma',
            constraint=models.UniqueConstraint(fields=('nome', 'ano_letivo', 'escola'), name='unique_turma_ano_escola'),
        ),
        migrations.AddConstraint(
            model_name='alunoturma',
            constraint=models.UniqueConstraint(fields=('aluno', 'turma'), name='unique_aluno_turma'),
        ),
    ]
