# Generated by Django 6.0.2 on 2026-02-04 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0001_initial'),
        ('people', '0002_etapa3_operacional'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('data_matricula', models.DateField(verbose_name='data da matricula')),
                ('tipo', models.CharField(choices=[('inicial', 'Inicial'), ('transferencia', 'Transferencia'), ('remanejamento', 'Remanejamento')], default='inicial', max_length=20, verbose_name='tipo')),
                ('status', models.CharField(choices=[('ativa', 'Ativa'), ('encerrada', 'Encerrada'), ('cancelada', 'Cancelada')], default='ativa', max_length=20, verbose_name='status')),
                ('observacao', models.TextField(blank=True, verbose_name='observacao')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matriculas', to='people.aluno', verbose_name='aluno')),
                ('ano_letivo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matriculas', to='academic.anoletivo', verbose_name='ano letivo')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matriculas', to='academic.turma', verbose_name='turma')),
            ],
            options={
                'verbose_name': 'matricula',
                'verbose_name_plural': 'matriculas',
                'ordering': ['-data_matricula', 'aluno'],
            },
        ),
        migrations.CreateModel(
            name='MovimentacaoAluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('tipo_evento', models.CharField(choices=[('matricula_inicial', 'Matricula inicial'), ('transferencia_entrada', 'Transferencia (entrada)'), ('transferencia_saida', 'Transferencia (saida)'), ('remanejamento', 'Remanejamento'), ('encerramento', 'Encerramento'), ('cancelamento', 'Cancelamento')], max_length=30, verbose_name='tipo de evento')),
                ('data', models.DateField(verbose_name='data')),
                ('descricao', models.TextField(verbose_name='descricao')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes', to='people.aluno', verbose_name='aluno')),
                ('matricula', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes', to='academic.matricula', verbose_name='matricula relacionada')),
            ],
            options={
                'verbose_name': 'movimentacao do aluno',
                'verbose_name_plural': 'movimentacoes de alunos',
                'ordering': ['-data', 'aluno'],
            },
        ),
        migrations.AddConstraint(
            model_name='matricula',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'ativa')), fields=('aluno', 'ano_letivo'), name='unique_matricula_ativa_por_ano'),
        ),
    ]
