# Generated by Django 6.0.2 on 2026-02-05 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0002_etapa3_operacional'),
        ('people', '0002_etapa3_operacional'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeHoraria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('ativa', models.BooleanField(default=True, verbose_name='ativa')),
                ('observacao', models.TextField(blank=True, default='', verbose_name='observacao')),
                ('ano_letivo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grades_horarias', to='academic.anoletivo', verbose_name='ano letivo')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grades_horarias', to='academic.turma', verbose_name='turma')),
            ],
            options={
                'verbose_name': 'grade horaria',
                'verbose_name_plural': 'grades horarias',
                'ordering': ['ano_letivo', 'turma'],
            },
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('ordem', models.PositiveSmallIntegerField(verbose_name='ordem')),
                ('hora_inicio', models.TimeField(verbose_name='hora de inicio')),
                ('hora_fim', models.TimeField(verbose_name='hora de fim')),
                ('turno', models.CharField(choices=[('M', 'Matutino'), ('V', 'Vespertino'), ('N', 'Noturno'), ('I', 'Integral')], default='M', max_length=1, verbose_name='turno')),
            ],
            options={
                'verbose_name': 'horario',
                'verbose_name_plural': 'horarios',
                'ordering': ['turno', 'ordem'],
                'constraints': [models.UniqueConstraint(fields=('turno', 'ordem'), name='unique_turno_ordem')],
            },
        ),
        migrations.CreateModel(
            name='GradeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('dia_semana', models.CharField(choices=[('SEG', 'Segunda-feira'), ('TER', 'Terca-feira'), ('QUA', 'Quarta-feira'), ('QUI', 'Quinta-feira'), ('SEX', 'Sexta-feira'), ('SAB', 'Sabado')], max_length=3, verbose_name='dia da semana')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grade_itens', to='academic.disciplina', verbose_name='disciplina')),
                ('grade_horaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='academic.gradehoraria', verbose_name='grade horaria')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grade_itens', to='people.professor', verbose_name='professor')),
                ('horario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grade_itens', to='academic.horario', verbose_name='horario')),
            ],
            options={
                'verbose_name': 'item da grade',
                'verbose_name_plural': 'itens da grade',
                'ordering': ['grade_horaria', 'dia_semana', 'horario__ordem'],
            },
        ),
        migrations.AddConstraint(
            model_name='gradehoraria',
            constraint=models.UniqueConstraint(condition=models.Q(('ativa', True)), fields=('turma', 'ano_letivo'), name='unique_grade_ativa_turma_ano'),
        ),
        migrations.AddConstraint(
            model_name='gradeitem',
            constraint=models.UniqueConstraint(fields=('grade_horaria', 'dia_semana', 'horario'), name='unique_grade_dia_horario'),
        ),
    ]
